baseURL = "/"
relativeURLs = true
languageCode = 'en-us'
title = 'Leenstx'
theme = 'yinyang'

[author]
  name = "Leenstx·"
  homepage = "https://leenstx.github.io/"

[params]
mainSections = ["posts"]

icp = "京ICP备20024809号"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "Github"
link = "https://github.com/leenstx/iblog"
